### ISSUE TITLE
L'inscription ne fonctionne pas

### ISSUE THREAD

**Issue by guillaumeperes** [melninie/QRCodeProjet#2]
http://qrcode.guillaumeperes.fr/signup

![9gclnbpfseghyilstx_x9q](https://user-images.githubusercontent.com/13225806/33230941-e8d46292-d1ec-11e7-9500-34575d7e7a6c.png)

**Comment by melninie** [comment]
C'est normal, on a décidé de l'enlever, c'est maintenant l'admin qui créé le users

**Comment by guillaumeperes** [comment]
Ok, mais dans ce cas pour éviter les erreurs il faudrait peut-être retirer les boutons qui permettaient d'accéder au formulaire d'inscription.

Il y en a deux : un sur la page d'accueil et un autre en dessous du formulaire de connexion. :)

**Comment by melninie** [comment]
Yes je vais le faire ;)
