### ISSUE TITLE
Connesion à VT

### ISSUE THREAD

**Issue by Desiderius77** [melninie/QRCodeProjet#3]
Bonjour,

Que voudriez-vous récupérer exactement de VT ? 
- les séances du jour d'une filière ?
- les séances d'un prof donné ?
- ..

Je vais me renseigner sur les APIs possibles ; A priori, VT Agenda qui propulse https:/:edt;univ-evry.fr est une application PHP qui interroge la base par PHP par une interface de type REST

**Comment by melninie** [comment]
Bonjour, 
En effet, nous aurions besoin de récupérer, les séances du jour d'une filière et les séances du jour d'un prof.
Il faudra je pense cependant voir comment faire le lien entre les filières et prof de notre application avec ceux de VT.

Merci

**Comment by Desiderius77** [comment]
J'ai demandé à Florent Perciot qui administre la base VT de l'Université.
Il va me fournir le dump XML de la base que vous pourrez utiliser pour peupler les filières et les profs.
mais il ne connait pas les APIs.
Je vais demander à Bruno Million qui a développé VT Agenda s'il a utilisé una API publique ou pas ou si vous pourriez utiliser une des ses APIs.
Je vous teins au courant
